AdvancedEshop/AdvancedEshop.Web/Models/Cart.cs
using AdvancedEshop.Web.API.Models;

namespace AdvancedEshop.Web.Models
{
    public class Cart
    {

        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        

        public virtual void AddItem(Product product, int quantity)
        {
            // Kiểm tra Lines trước khi thao tác
            if (Lines == null)
            {
                Lines = new List<CartLine>();
            }

            CartLine line = Lines
                .FirstOrDefault(p => p.Product.ProductId == product.ProductId);

            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void GiamItem(Product product, int quantity)
        {
            CartLine line = Lines
                .FirstOrDefault(p => p.Product.ProductId == product.ProductId);

            if (line != null)
            {
                if (line.Quantity > quantity)
                {
                    line.Quantity -= quantity;
                }
                else
                {
                    RemoveLine(product);
                }
            }
        }





        public virtual void RemoveLine(Product product)
        {
            // Kiểm tra Lines trước khi thao tác
            if (Lines == null)
            {
                Lines = new List<CartLine>();
            }

            Lines.RemoveAll(l => l.Product.ProductId == product.ProductId);
        }

        public decimal ComputeTotalValue()
        {
            // Kiểm tra Lines trước khi tính toán
            if (Lines == null)
            {
                Lines = new List<CartLine>();
            }

            return (decimal)Lines.Sum(line => line.Product.ProductPrice*(1- line.Product.ProductDiscount) * line.Quantity);
        }

        public virtual void Clear()
        {
            // Kiểm tra Lines trước khi xóa
            if (Lines == null)
            {
                Lines = new List<CartLine>();
            }

            Lines.Clear();
        }

        //internal void RemoveLine(object product)
        //{
        //    throw new NotImplementedException();
        //}
    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; } = new Product();
        public int Quantity { get; set; }
    }

}

AdvancedEshop/AdvancedEshop.Web/Controllers/OrderController.cs
using AdvancedEshop.Web.API.Models;
using AdvancedEshop.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdvancedEshop.Web.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
           
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

AdvancedEshop/AdvancedEshop.Web/Pages/Cart.cshtml.cs
using AdvancedEshop.Web.API.Models;
using AdvancedEshop.Web.Infrastructure;
using AdvancedEshop.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Migrations;
using Newtonsoft.Json;
using NuGet.Protocol.Core.Types;

namespace AdvancedEshop.Web.Pages
{
    public class CartModel : PageModel
    {
        private IOrderRepository repository;
        private readonly IHttpClientFactory _clientFactory;
        public CartModel(IOrderRepository repo, Cart cartService, IHttpClientFactory clientFactory)
        {
            repository = repo;
            Cart = cartService;
            _clientFactory = clientFactory;
        }
       

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        /*public async Task<IActionResult> Index()
        {
            return RedirectToPage("/Cart", HttpContext.Session.GetJson<Cart>("cart"));
        }*/



        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product? product = repository.Products
            .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
            cl.Product.ProductId == productId).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }




        public IActionResult OnPostAdd(long productId, string returnUrl)
        {
            Product? product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                Cart.AddItem(product, 1);
                // Thêm log hoặc điểm chèn để kiểm tra
                Console.WriteLine($"Added product {productId} to the cart.");
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostGiam(long productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                Cart.GiamItem(product, 1);
            }

            return RedirectToPage(new { returnUrl = returnUrl });
        }







        /*public async Task<IActionResult> OnPostAddToCartAsync(int id)
        {
            var client = _clientFactory.CreateClient();

            var response = await client.GetAsync($"https://localhost:7136/products2/{id}");
            response.EnsureSuccessStatusCode();

            var content = await response.Content.ReadAsStringAsync();
            var product = JsonConvert.DeserializeObject<Product>(content);

            // Cập nhật giỏ hàng
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(product, 1);
            HttpContext.Session.SetJson("cart", Cart);

            // Chuyển hướng sang view "Cart" với thông tin giỏ hàng
            return RedirectToPage("/Cart", new { returnUrl = ReturnUrl });
        }

        public async Task<IActionResult> OnPostUpdateCartAsync(int id)
        {
            var client = _clientFactory.CreateClient();

            var response = await client.GetAsync($"https://localhost:7136/products2/{id}");
            response.EnsureSuccessStatusCode();

            var content = await response.Content.ReadAsStringAsync();
            var product = JsonConvert.DeserializeObject<Product>(content);

            // Cập nhật giỏ hàng
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.UpdateLine(product, 1); // Tăng số lượng lên 1
            HttpContext.Session.SetJson("cart", Cart);

            // Chuyển hướng sang trang "Cart" với thông tin giỏ hàng
            return RedirectToPage("/Cart", Cart);
        }*/


    }


}

AdvancedEshop/AdvancedEshop.Web/Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdvancedEshop.Web.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AdvancedEshop/AdvancedEshop.Web/Pages/Cart.cshtml
@page
@using AdvancedEshop.Web.Pages;
@model CartModel

<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @foreach (var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
                    {
                        <tr>
                            <td class="align-middle">
                                <img src="@line.Product.ProductPhoto" alt="" style="width: 50px;">
                                @line.Product.ProductName
                            </td>
                            <td class="align-middle">@(line.Product.ProductPrice * (1 - line.Product.ProductDiscount))</td>
                            <td class="">
                                <form asp-page-handler="Giam" method="post">
                                    <input type="hidden" name="ProductId" value="@line.Product.ProductId" />
                                    <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl" />
                                    <button type="submit" class="btn btn-sm btn-primary btn-minus">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </form>


                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        
                                        

                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="@line.Quantity">
                                    <div class="input-group-btn">
                                        


                                    </div>
                                </div>
                                <form asp-page-handler="Add" method="post">
                                    <input type="hidden" name="ProductId" value="@line.Product.ProductId" />
                                    <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl" />
                                    <button type="submit" class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </form>
                            </td>
                            <td class="align-middle">$@(line.Product.ProductPrice * (1 - line.Product.ProductDiscount) * line.Quantity)</td>
                            <td class="align-middle">
                                <form asp-page-handler="Remove" method="post">
                                    <input type="hidden" name="ProductId" value="@line.Product.ProductId" />
                                    <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl" />
                                    <button type="submit" class="btn btn-sm btn-primary">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </form>

                               @*  <a asp-page-handler="OnPostRemoveFromCartAsync" asp-page="/Cart" asp-route-id="@line.Product.ProductId" class="btn btn-sm btn-primary">
                                    <i class="fa fa-times"></i>
                                </a> *@
                            </td>


                        </tr>
                    }
                    <a class="btn btn-primary" href="@Model.ReturnUrl">
                        Continue shopping
                    </a>
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">@Model.Cart?.ComputeTotalValue().ToString("c")</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">$@(@Model.Cart?.ComputeTotalValue() + 10)</h5>
                    </div>
                    @* <button class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</button> *@
                    <a class="btn btn-block btn-primary my-3 py-3" asp-action="Checkout" asp-controller="Order">
                        Proceed To Checkout
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

AdvancedEshop/AdvancedEshop.Web/Pages/Completed.cshtml
@page
<div class="text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing order #@OrderId</p>
    <p>We"ll ship your goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}